version: '2.1'
volumes:
    security-camera-data: {}
services:
    cv:
        build:
            context: cv
            dockerfile: Dockerfile.template
        privileged: true
        network_mode: host
        depends_on:
            - "server"
        volumes:
            - "security-camera-data:/app/data"
        devices:
            - "/dev:/dev"
    server:
        build:
            context: server
            dockerfile: Dockerfile.template
        privileged: true
        network_mode: host
        volumes:
            - "security-camera-data:/app/data"
