FROM alwaysai/edgeiq:0.7.20
# Update timezone so timestamps make sense
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# Enable UDEV for NCS
ENV UDEV=1

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . ./
CMD ["python3", "-u", "app.py", "--engine", "DNN"]
