#FROM balenalib/raspberrypi3-debian-python:3.5.7-stretch-build
FROM balenalib/amd64-debian-python:3.5.7-stretch-build
RUN sudo apt-get update && sudo apt-get install -y cmake

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . ./
CMD ["python3", "-u", "server.py"]
